### ISSUE TITLE
ETE3 dependency and missing link(s)

### ISSUE THREAD

**Issue by jdarias93** [mossmatters/MJPythonNotebooks#1]
Hello,

I know this isn't a PhyParts PieCharts issue, but perhaps someone could give me some advice on how to fix the problem or direct me to another resource where I can get more help?

> $ conda install -c etetoolkit ete3 ete3_external_apps 
> Fetching package metadata ...........
> Solving package specifications: .
> 
> UnsatisfiableError: The following specifications were found to be in conflict:
>   - ete3_external_apps -> python 2.7* -> openssl 1.0.1*
>   - python 3.6*
> Use "conda info <package>" to see the dependencies for each package.

Also, at the end of the PhyParts page, it says that I can find links to the script but the "here" has no hyperlink. The "Download" button links me to the raw github script--would I just need to save the link as a ".py" file? 

Thanks in advance!

**Comment by mossmatters** [comment]
Thanks for pointing out the missing link, the script is here: https://github.com/mossmatters/MJPythonNotebooks/blob/master/phypartspiecharts.py

I also updated it recently to allow more fine-tuning of colors in the pie charts.

As for installing ete, you may want to try the ete page: 

https://github.com/etetoolkit/ete/issues

Although you may be able to get around it by not including the external apps. You won't need them for my script, and you can always install them separately later.
